CREATE DATABASE AcademyLibrary
GO
USE AcademyLibrary
GO

CREATE TABLE LIBRARY_BRANCH (
	BranchID			INT PRIMARY KEY						NOT NULL	IDENTITY (101,1),
	BranchName			VARCHAR(50)							NOT NULL,
	Address				VARCHAR(200)						NOT NULL
);

CREATE TABLE PUBLISHER (
	PublisherName		VARCHAR(50)	PRIMARY KEY				NOT NULL,
	Address				VARCHAR(200)						NOT NULL,
	Phone				BIGINT								NOT NULL,
);

CREATE TABLE BOOKS (
	BookID				INT PRIMARY KEY						NOT NULL	IDENTITY (1,1),
	Title				VARCHAR(150)						NOT NULL,
	PublisherName		VARCHAR(50)							NOT NULL	CONSTRAINT fk_BOOKS_PublisherName
						FOREIGN KEY REFERENCES	PUBLISHER(PublisherName) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE BOOK_AUTHORS (
	BookID				INT									NOT NULL	CONSTRAINT fk_BOOK_AUTHORS_BookID
						FOREIGN KEY REFERENCES BOOKS(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName			VARCHAR(50)							NOT NULL
);

CREATE TABLE BOOK_COPIES (
	BookID				INT									NOT NULL	CONSTRAINT fk_BOOK_COPIES_BookID
						FOREIGN KEY REFERENCES BOOKS(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID			INT									NOT NULL	CONSTRAINT fk_BOOK_COPIES_BranchID
						FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	Number_Of_Copies	INT									NOT NULL
);

CREATE TABLE BORROWER (
	CardNo				INT PRIMARY KEY						NOT NULL	IDENTITY(1000,1),
	Name				VARCHAR(100)						NOT NULL,
	Address				VARCHAR(200)						NOT NULL,
	Phone				BIGINT									NOT NULL
);

CREATE TABLE BOOK_LOANS (
	BookID				INT									NOT NULL	CONSTRAINT fk_BOOK_LOANS_BookID
						FOREIGN KEY REFERENCES BOOKS(BookID)			ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID			INT									NOT NULL	CONSTRAINT fk_BOOK_LOANS_BranchID
						FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchID)	ON UPDATE CASCADE ON DELETE CASCADE,
	CardNo				INT									NOT NULL	CONSTRAINT fk_BOOK_LOANS_CardNo
						FOREIGN KEY REFERENCES BORROWER(CardNo)			ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut				DATE								NOT NULL,
	DateDue				DATE								NOT NULL
);
